#line 1 "./templates/my_index.tmpl"
#include "../content.h" 
#line 2 "./templates/my_index.tmpl"
namespace my_index {
	#line 3 "./templates/my_index.tmpl"
	struct index :public cppcms::base_view
	#line 3 "./templates/my_index.tmpl"
	{
	#line 3 "./templates/my_index.tmpl"
		content::index_content &content;
	#line 3 "./templates/my_index.tmpl"
		index(std::ostream &_s,content::index_content &_content): cppcms::base_view(_s),content(_content)
	#line 3 "./templates/my_index.tmpl"
		{
	#line 3 "./templates/my_index.tmpl"
		}
		#line 4 "./templates/my_index.tmpl"
		virtual void render() {
			#line 102 "./templates/my_index.tmpl"
			out()<<"\n"
				"<!DOCTYPE html>\n"
				"<html>\n"
				"<body>\n"
				"<head>\n"
				"\t<title>Visibility Query</title>\n"
				"\t\t<meta charset=\"utf-8\">\n"
				"\t\t<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\">\n"
				"\t\t<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\n"
				"\t\t<link href=\"/simple-sidebar.css\" rel=\"stylesheet\">\n"
				"\t\t<style>\n"
				"\t\t\t.boxcorner {\n"
				"\t\t\t\tborder-radius: 20px;\n"
				"    \t\t\tborder-left: 2px solid #606060;\n"
				"    \t\t\tborder-right: 2px solid #606060;\n"
				"    \t\t\tborder-bottom: 2px solid #606060;\n"
				"    \t\t\tmargin-top: 10px;\n"
				"    \t\t\tpadding-top: 10px;\n"
				"    \t\t\tpadding-left: 10px;\n"
				"    \t\t\tpadding-bottom: 10px;\n"
				"\n"
				"\n"
				"\t\t\t}\n"
				"\t\t\t.custrow {\n"
				"    \t\t\tpadding-top: 5px;\n"
				"    \t\t\tpadding-bottom: 5px;\n"
				"\n"
				"\n"
				"\t\t\t}\n"
				"\t\t\t.table td{\n"
				"\t\t\t    border-bottom: #606060 solid 0.5px !important;\n"
				"\t\t\t}\n"
				"\t\t\t.table th{\n"
				"\t\t\t    border-top: #606060 solid 0.5px !important;\n"
				"\t\t\t    border-bottom: #606060 solid 0.5px !important;\n"
				"\t\t\t}\n"
				"\t\t\t\n"
				"\t\t\tbody {\n"
				"\t\t\t\tbackground-color: #f0f0f0;\n"
				"\t\t\t\tmargin: 0px;\n"
				"\t\t\t\toverflow: hidden;\n"
				"\t\t\t}\n"
				"\t\t</style>\n"
				"</head>\n"
				"<body onload=\"onload()\">\n"
				"<script\n"
				"  src=\"https://code.jquery.com/jquery-3.1.1.min.js\"\n"
				"  integrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"\n"
				"  crossorigin=\"anonymous\"></script>\n"
				"<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\n"
				"\n"
				"<script src=\"/build/three.js\"></script>\n"
				"<script src=\"/js/utils/GeometryUtils.js\"></script>\n"
				"\n"
				"<script src=\"/js/renderers/Projector.js\"></script>\n"
				"<script src=\"/js/renderers/CanvasRenderer.js\"></script>\n"
				"\n"
				"<script src=\"/js/controls/OrbitControls.js\"></script>\n"
				"<script src=\"/js/Detector.js\"></script>\n"
				"\n"
				"<script src=\"/js/libs/stats.min.js\"></script>\n"
				"<script src=\"/myCamera/myCamera.js\"></script>\n"
				"\n"
				"<div id=\"wrapper\">\n"
				"\t<div id=\"sidebar-wrapper\">\n"
				"\t\t<ul class=\"sidebar-nav\">\n"
				"\t\t\t<li class=\"sidebar-brand\">\n"
				"\t\t\t\t<a href=\"\">VizQ3D</a>\n"
				"\t\t\t</li>\n"
				"\t\t</ul>\n"
				"        <div class=\"container-fluid settings\" style=\"margin-top: 70px;\">\n"
				"        \t<div class=\"row boxcorner\" >\n"
				"        \t\t<div class=\"col-lg-6\">\n"
				"        \t\t\tMode\n"
				"        \t\t</div>\n"
				"        \t\t<div class=\"col-offset-lg-1 col-lg-5\">\n"
				"        \t\t\t<select name=\"mode\" id=\"mode\" class=\"form-control\" onchange=\"modeChange()\">\n"
				"\t\t\t\t\t\t<option value=\"mvq\">MVQ</option>\n"
				"\t\t\t\t\t\t<option value=\"vcm\">VCM</option>\n"
				"\t\t\t\t\t\t<option value=\"tvcm\">TVCM</option>\n"
				"\t\t\t\t\t\t<option value=\"cmvq\">CMVQ(2D)</option>\n"
				"\t\t\t\t\t</select>\n"
				"        \t\t</div>\n"
				"        \t</div>\n"
				"            \n"
				"           \n"
				"            \t\n"
				"            \t <br>\n"
				"\t            \t<div class=\"row\">\n"
				"\t            \t\t<div class=\"col-lg-12\">\n"
				"\t            \t\t\tObstacle Set\n"
				"\t            \t\t</div>\n"
				"\t            \t</div>\n"
				"            \t<div class=\"boxcorner\">\n"
				"\t            \t<div class=\"row custrow\">\n"
				"\t            \t\t<div class=\"col-lg-1\"></div>\n"
				"\t            \t\t<div class=\"col-lg-7\">\n"
				"\t            \t\t\t<select name=\"ob\" id=\"ob\" class=\"form-control\">\n"
				"\t\t\t\t\t\t\t";
			#line 102 "./templates/my_index.tmpl"
			if((content.ob).begin()!=(content.ob).end()) {
				#line 103 "./templates/my_index.tmpl"
				out()<<"\n"
					"                            ";
				#line 103 "./templates/my_index.tmpl"
				for(CPPCMS_TYPEOF((content.ob).begin()) o_ptr=(content.ob).begin(),o_ptr_end=(content.ob).end();o_ptr!=o_ptr_end;++o_ptr) {
				#line 103 "./templates/my_index.tmpl"
				CPPCMS_TYPEOF(*o_ptr) &o=*o_ptr;
					#line 104 "./templates/my_index.tmpl"
					out()<<"\n"
						"\t\t\t\t\t\t\t\t<option value=\"";
					#line 104 "./templates/my_index.tmpl"
					out()<<cppcms::filters::escape(o);
					#line 104 "./templates/my_index.tmpl"
					out()<<"\">";
					#line 104 "./templates/my_index.tmpl"
					out()<<cppcms::filters::escape(o);
					#line 105 "./templates/my_index.tmpl"
					out()<<"</option>\n"
						"                            ";
				#line 105 "./templates/my_index.tmpl"
				} // end of item
				#line 106 "./templates/my_index.tmpl"
				out()<<"\n"
					"\t\t\t\t\t\t\t";
			#line 106 "./templates/my_index.tmpl"
			}
			#line 140 "./templates/my_index.tmpl"
			out()<<"\n"
				"\t\t\t\t\t\t\t</select>\n"
				"\t            \t\t</div>\n"
				"\t            \t\t<div class=\"col-lg-3\">\n"
				"\t            \t\t\t<button class=\"btn btn-md btn-primary\" onclick=\"loadDB()\">Load</button>\n"
				"\t            \t\t</div>\n"
				"\t            \t</div>\n"
				"\t\t\t\t\t<!--\n"
				"\t            \t<div class=\"row custrow\">\n"
				"\t            \t\t<div class=\"col-lg-1\"></div>\n"
				"\t            \t\t<form class=\"form-inline\" action=\"/upload_ob\" method=\"post\" enctype=\"multipart/form-data\">\n"
				"\t            \t\t\t<div class=\"col-lg-8\">\n"
				"\t\t\t\t\t\t\t\t{% csrf_token %}\n"
				"\t\t\t\t\t\t\t\t{% for field in form %}\n"
				"\t\t\t\t\t\t\t\t\t{{ field }}\n"
				"\t\t\t\t\t\t\t\t{% endfor %}\n"
				"\t            \t\t\t</div>\n"
				"\t            \t\t\t<input type=\"hidden\" name=\"type\" value=\"ob\"/>\n"
				"\t            \t\t\n"
				"\t            \t\t\n"
				"\t            \t</div>\n"
				"\t\t\t\t\t\n"
				"\t            \t<div class=\"row custrow\">\n"
				"\t            \t\t<div class=\"col-lg-1\"></div>\n"
				"\t            \t\t<div class=\"col-lg-2\">\t\n"
				"\t            \t\t\t\t<button type=\"submit\" class=\"btn btn-md btn-primary\">Upload</button>\n"
				"\t            \t\t</div>\n"
				"\t            \t\t</form>\n"
				"\t            \t</div>\n"
				"\t\t\t\t\t-->\n"
				"\t\t\t\t\t<div class=\"row custrow\">\n"
				"\t\t\t\t\t\t<div class=\"col-lg-1\"></div>\n"
				"\t\t\t\t\t\t<div class=\"col-lg-8\">\n"
				"\t\t\t\t\t\t<form class=\"form-inline\" action=\"/hello/upload/ob\" method=\"post\" enctype=\"multipart/form-data\">\n"
				"\t\t\t\t\t\t\t";
			#line 140 "./templates/my_index.tmpl"
			{ cppcms::form_context _form_context(out(),cppcms::form_flags::as_html,cppcms::form_flags::as_p); (content.uploadfile).render(_form_context); }
			#line 164 "./templates/my_index.tmpl"
			out()<<"\n"
				"\t\t\t\t\t\t\t<div class=\"row custrow\">\n"
				"\t\t\t\t\t\t\t\t<div class=\"col-lg-2\">\t\n"
				"\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-md btn-primary\">Upload</button>\n"
				"\t\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t\t\t</form>\n"
				"\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t</form>\n"
				"\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t</div>\n"
				"            \t</div>\n"
				"\t\t\t\t\n"
				"\t\t\t<div id=\"cmvq_settings\" style=\"display: none;\">\n"
				"\t\t\t<br>\n"
				"\t            <div class=\"row\" >\n"
				"            \t\t<div class=\"col-lg-12\">\n"
				"            \t\t  \tTarget Path\n"
				"            \t\t</div>\n"
				"            \t</div>\n"
				"            \t<div class=\"boxcorner\">\n"
				"\t\t        \t<div class=\"row custrow\">\n"
				"\t\t        \t\t<div class=\"col-lg-1\"></div>\n"
				"\t\t        \t\t<div class=\"col-lg-7\">\n"
				"\t\t\t\t\t\t\t<select name=\"tp\" id=\"tp\" class=\"form-control\">\n"
				"\t\t\t\t\t\t\t\t";
			#line 164 "./templates/my_index.tmpl"
			if((content.tp).begin()!=(content.tp).end()) {
				#line 165 "./templates/my_index.tmpl"
				out()<<"\n"
					"\t\t\t\t\t\t\t\t";
				#line 165 "./templates/my_index.tmpl"
				for(CPPCMS_TYPEOF((content.tp).begin()) t_ptr=(content.tp).begin(),t_ptr_end=(content.tp).end();t_ptr!=t_ptr_end;++t_ptr) {
				#line 165 "./templates/my_index.tmpl"
				CPPCMS_TYPEOF(*t_ptr) &t=*t_ptr;
					#line 166 "./templates/my_index.tmpl"
					out()<<"\n"
						"\t\t\t\t\t\t\t\t\t<option value=\"";
					#line 166 "./templates/my_index.tmpl"
					out()<<cppcms::filters::escape(t);
					#line 166 "./templates/my_index.tmpl"
					out()<<"\">";
					#line 166 "./templates/my_index.tmpl"
					out()<<cppcms::filters::escape(t);
					#line 167 "./templates/my_index.tmpl"
					out()<<"</option>\n"
						"\t\t\t\t\t\t\t\t";
				#line 167 "./templates/my_index.tmpl"
				} // end of item
				#line 168 "./templates/my_index.tmpl"
				out()<<"\n"
					"\t\t\t\t\t\t\t\t";
			#line 168 "./templates/my_index.tmpl"
			}
			#line 202 "./templates/my_index.tmpl"
			out()<<"\n"
				"\t\t\t\t\t\t\t</select>\n"
				"\t\t        \t\t</div>\n"
				"\t\t        \t\t<div class=\"col-lg-3\">\n"
				"\t\t        \t\t\t<button class=\"btn btn-md btn-primary\" onclick=\"loadTP()\">Load</button>\n"
				"\t\t        \t\t</div>\n"
				"\t\t        \t</div>\n"
				"\t\t\t\t\t<!--\n"
				"\t\t        \t<div class=\"row custrow\">\n"
				"\t\t        \t\t<div class=\"col-lg-1\"></div>\n"
				"\t\t        \t\t<form class=\"form-inline\" action=\"/upload_tp\" method=\"post\" enctype=\"multipart/form-data\">\n"
				"\t\t        \t\t\t<div class=\"col-lg-9\">\n"
				"\t\t\t\t\t\t\t\t{% csrf_token %}\n"
				"\t\t\t\t\t\t\t\t{% for field in form %}\n"
				"\t\t\t\t\t\t\t\t\t{{ field }}\n"
				"\t\t\t\t\t\t\t\t{% endfor %}\n"
				"\t\t        \t\t\t</div>\n"
				"\t\t        \t\t\t<input type=\"hidden\" name=\"type\" value=\"tp\"/>\n"
				"\t\t        \t\t\n"
				"\t\t        \t\t\n"
				"\t\t        \t</div>\n"
				"\t\t\t\t\t\n"
				"\t\t        \t<div class=\"row custrow\">\n"
				"\t\t        \t\t<div class=\"col-lg-1\"></div>\n"
				"\t\t        \t\t<div class=\"col-lg-2\">\t\n"
				"\t\t    \t\t\t\t<button type=\"submit\" class=\"btn btn-md btn-primary\">Upload</button>\n"
				"\t\t    \t\t\t</div>\n"
				"\t\t    \t\t\t</form>\n"
				"\t\t        \t</div>\n"
				"\t\t\t\t\t-->\n"
				"\t\t\t\t\t<div class=\"row custrow\">\n"
				"\t\t\t\t\t\t<div class=\"col-lg-1\"></div>\n"
				"\t\t\t\t\t\t<div class=\"col-lg-8\">\n"
				"\t\t\t\t\t\t<form class=\"form-inline\" action=\"/hello/upload/tp\" method=\"post\" enctype=\"multipart/form-data\">\n"
				"\t\t\t\t\t\t\t";
			#line 202 "./templates/my_index.tmpl"
			{ cppcms::form_context _form_context(out(),cppcms::form_flags::as_html,cppcms::form_flags::as_p); (content.uploadfile).render(_form_context); }
			#line 230 "./templates/my_index.tmpl"
			out()<<"\n"
				"\t\t\t\t\t\t\t<div class=\"row custrow\">\n"
				"\t\t\t\t\t\t\t\t<div class=\"col-lg-2\">\t\n"
				"\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-md btn-primary\">Upload</button>\n"
				"\t\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t\t\t</form>\n"
				"\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t</form>\n"
				"\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t</div>\n"
				"\n"
				"            \t</div>\t\n"
				"\n"
				"\t\t\t</div>\n"
				"            \n"
				"            \n"
				"            <div id=\"query_locations\" style=\"display: none;\">\n"
				"\t\t\t<br>\n"
				"\t            <div class=\"row\" >\n"
				"            \t\t<div class=\"col-lg-12\">\n"
				"            \t\t  \tQuery Locations\n"
				"            \t\t</div>\n"
				"            \t</div>\n"
				"            \t<div class=\"boxcorner\">\n"
				"\t\t        \t<div class=\"row custrow\">\n"
				"\t\t        \t\t<div class=\"col-lg-1\"></div>\n"
				"\t\t        \t\t<div class=\"col-lg-7\">\n"
				"\t\t\t\t\t\t\t<select name=\"qp\" id=\"qp\" class=\"form-control\">\n"
				"\t\t\t\t\t\t\t\t";
			#line 230 "./templates/my_index.tmpl"
			if((content.qp).begin()!=(content.qp).end()) {
				#line 231 "./templates/my_index.tmpl"
				out()<<"\n"
					"\t\t\t\t\t\t\t\t";
				#line 231 "./templates/my_index.tmpl"
				for(CPPCMS_TYPEOF((content.qp).begin()) q_ptr=(content.qp).begin(),q_ptr_end=(content.qp).end();q_ptr!=q_ptr_end;++q_ptr) {
				#line 231 "./templates/my_index.tmpl"
				CPPCMS_TYPEOF(*q_ptr) &q=*q_ptr;
					#line 232 "./templates/my_index.tmpl"
					out()<<"\n"
						"\t\t\t\t\t\t\t\t\t<option value=\"";
					#line 232 "./templates/my_index.tmpl"
					out()<<cppcms::filters::escape(q);
					#line 232 "./templates/my_index.tmpl"
					out()<<"\">";
					#line 232 "./templates/my_index.tmpl"
					out()<<cppcms::filters::escape(q);
					#line 233 "./templates/my_index.tmpl"
					out()<<"</option>\n"
						"\t\t\t\t\t\t\t\t";
				#line 233 "./templates/my_index.tmpl"
				} // end of item
				#line 234 "./templates/my_index.tmpl"
				out()<<"\n"
					"\t\t\t\t\t\t\t\t";
			#line 234 "./templates/my_index.tmpl"
			}
			#line 268 "./templates/my_index.tmpl"
			out()<<"\n"
				"\t\t\t\t\t\t\t</select>\n"
				"\t\t        \t\t</div>\n"
				"\t\t        \t\t<div class=\"col-lg-3\">\n"
				"\t\t        \t\t\t<button class=\"btn btn-md btn-primary\" onclick=\"loadQP()\">Load</button>\n"
				"\t\t        \t\t</div>\n"
				"\t\t        \t</div>\n"
				"\t\t\t\t\t<!-- \n"
				"\t\t        \t<div class=\"row custrow\">\n"
				"\t\t        \t\t<div class=\"col-lg-1\"></div>\n"
				"\t\t        \t\t<form class=\"form-inline\" action=\"/upload_qp\" method=\"post\" enctype=\"multipart/form-data\">\n"
				"\t\t        \t\t\t<div class=\"col-lg-9\">\n"
				"\t\t\t\t\t\t\t\t{% csrf_token %}\n"
				"\t\t\t\t\t\t\t\t{% for field in form %}\n"
				"\t\t\t\t\t\t\t\t\t{{ field }}\n"
				"\t\t\t\t\t\t\t\t{% endfor %}\n"
				"\t\t        \t\t\t</div>\n"
				"\t\t        \t\t\t<input type=\"hidden\" name=\"type\" value=\"qp\"/>\n"
				"\t\t        \t\t\n"
				"\t\t        \t\t\n"
				"\t\t        \t</div>\n"
				"\t\t\t\t\t\n"
				"\t\t        \t<div class=\"row custrow\">\n"
				"\t\t        \t\t<div class=\"col-lg-1\"></div>\n"
				"\t\t        \t\t<div class=\"col-lg-2\">\t\n"
				"\t\t    \t\t\t\t<button type=\"submit\" class=\"btn btn-md btn-primary\">Upload</button>\n"
				"\t\t    \t\t\t</div>\n"
				"\t\t    \t\t\t</form>\n"
				"\t\t        \t</div>\n"
				"\t\t\t\t\t-->\n"
				"\t\t\t\t\t<div class=\"row custrow\">\n"
				"\t\t\t\t\t\t<div class=\"col-lg-1\"></div>\n"
				"\t\t\t\t\t\t<div class=\"col-lg-8\">\n"
				"\t\t\t\t\t\t<form class=\"form-inline\" action=\"/hello/upload/qp\" method=\"post\" enctype=\"multipart/form-data\">\n"
				"\t\t\t\t\t\t\t";
			#line 268 "./templates/my_index.tmpl"
			{ cppcms::form_context _form_context(out(),cppcms::form_flags::as_html,cppcms::form_flags::as_p); (content.uploadfile).render(_form_context); }
			#line 330 "./templates/my_index.tmpl"
			out()<<"\n"
				"\t\t\t\t\t\t\t<div class=\"row custrow\">\n"
				"\t\t\t\t\t\t\t\t<div class=\"col-lg-2\">\t\n"
				"\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-md btn-primary\">Upload</button>\n"
				"\t\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t\t\t</form>\n"
				"\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t</form>\n"
				"\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\n"
				"            \t</div>\n"
				"            \t<div class=\"row boxcorner\">\n"
				"            \t\t<div class=\"col-lg-5\">\n"
				"            \t\t\tResults (k)\n"
				"            \t\t</div>\n"
				"            \t\t<div class=\"col-lg-3\">\n"
				"            \t\t\t<input class=\"form-control\" type=\"text\" name=\"k\" id=\"k\" size=\"2\" />\n"
				"            \t\t</div>\n"
				"            \t</div>\n"
				"            \t<div class=\"row boxcorner cmvq\">\n"
				"            \t\t<div class=\"col-lg-5\">\n"
				"            \t\t\tField of View (FOV)\n"
				"            \t\t</div>\n"
				"            \t\t<div class=\"col-lg-3\">\n"
				"            \t\t\t<input class=\"form-control\" type=\"text\" name=\"fov\" id=\"fov\" size=\"4\" />\n"
				"            \t\t</div>\n"
				"            \t</div>\n"
				"\n"
				"\t\t\t</div>\n"
				"\n"
				"\n"
				"            <div id=\"vcm_settings\" class=\"boxcorner\" >\n"
				"\t\t\t\t<div class=\"row\">\n"
				"\t\t\t\t\t<div class=\"col-lg-2\">\n"
				"\t\t\t\t\t\tAxis\n"
				"\t\t\t\t\t</div>\n"
				"\t\t\t\t\t<div class=\"col-lg-5\">\n"
				"\t\t\t\t\t\t<select name=\"axis\" id=\"axis\" class=\"form-control\" onchange=\"axisChange()\">\n"
				"\t\t\t\t\t\t<option value=\"0\">-X</option>\n"
				"\t\t\t\t\t\t<option value=\"1\">+X</option>\n"
				"\t\t\t\t\t\t<option value=\"2\">-Y</option>\n"
				"\t\t\t\t\t\t<option value=\"3\">+Y</option>\n"
				"\t\t\t\t\t\t<option value=\"4\">-Z</option>\n"
				"\t\t\t\t\t\t<option value=\"5\">+Z</option>\n"
				"\t\t\t\t\t</select>\n"
				"\t\t\t\t\t</div>\n"
				"\t\t\t\t</div>\n"
				"\t\t\t</div>\n"
				"\t\t\t<div id=\"tvcm_settings\" class=\"boxcorner\">\n"
				"\n"
				"\t\t\t\t<div  class=\"row custrow\">\n"
				"\t\t\t\t\t<div class=\"col-lg-12\" id=\"texts\">\n"
				"\t\t\t\t\t\t<div id=\"t1\" class=\"row custrow\">\n"
				"\t\t\t\t\t\t\t<div class=\"col-lg-2\">\n"
				"\t\t\t\t\t\t\t\tText\n"
				"\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t\t<div class=\"col-lg-6\">\n"
				"\t\t\t\t\t\t\t\t<input type=\"text\" name=\"vcm_text\" id=\"vcm_text\" class=\"form-control\" />\n"
				"\t\t\t\t\t\t\t</div> \n"
				"\t\t\t\t\t\t\t<div class=\"col-lg-4\" style=\"float:right;\">\n"
				"\t\t\t\t\t\t\t\t<select name=\"fontsize\" id=\"fontsize\" class=\"form-control\" >\n"
				"\t\t\t\t\t\t\t\t";
			#line 330 "./templates/my_index.tmpl"
			if(!(content.fontsize.empty())) {
				#line 331 "./templates/my_index.tmpl"
				out()<<"\n"
					"\t\t\t\t\t\t\t\t\t";
				#line 331 "./templates/my_index.tmpl"
				if((content.fontsize).begin()!=(content.fontsize).end()) {
					#line 332 "./templates/my_index.tmpl"
					out()<<"\n"
						"\t\t\t\t\t\t\t\t\t\t";
					#line 332 "./templates/my_index.tmpl"
					for(CPPCMS_TYPEOF((content.fontsize).begin()) f_ptr=(content.fontsize).begin(),f_ptr_end=(content.fontsize).end();f_ptr!=f_ptr_end;++f_ptr) {
					#line 332 "./templates/my_index.tmpl"
					CPPCMS_TYPEOF(*f_ptr) &f=*f_ptr;
						#line 333 "./templates/my_index.tmpl"
						out()<<"\n"
							"\t\t\t\t\t\t\t\t\t\t\t<option value=\"";
						#line 333 "./templates/my_index.tmpl"
						out()<<cppcms::filters::escape(f);
						#line 333 "./templates/my_index.tmpl"
						out()<<"\">";
						#line 333 "./templates/my_index.tmpl"
						out()<<cppcms::filters::escape(f);
						#line 334 "./templates/my_index.tmpl"
						out()<<"</option>\n"
							"\t\t\t\t\t\t\t\t\t\t";
					#line 334 "./templates/my_index.tmpl"
					} // end of item
					#line 335 "./templates/my_index.tmpl"
					out()<<"\n"
						"\t\t\t\t\t\t\t\t\t";
				#line 335 "./templates/my_index.tmpl"
				}
				#line 336 "./templates/my_index.tmpl"
				out()<<"\n"
					"\t\t\t\t\t\t\t\t";
			#line 336 "./templates/my_index.tmpl"
			} // endif
			#line 392 "./templates/my_index.tmpl"
			out()<<"\n"
				"\t\t\t\t\t\t\t</select>\n"
				"\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t\t<br>\n"
				"\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t</div>\n"
				"\t\t\t\t\t<div class=\"col-lg-12\">\n"
				"\t\t\t\t\t\t<div class=\"row custrow\">\n"
				"\t\t\t\t\t\t\t<div class=\"col-lg-2\">\n"
				"\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t\t<div class=\"col-lg-7\">\n"
				"\t\t\t\t\t\t\t\t<button class=\"btn btn-md btn-primary\" onclick=\"loadText()\">Load</button>\n"
				"\t\t\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\t\t<div class=\"col-lg-1\">\n"
				"\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-xs btn-default\" aria-label=\"Left Align\" onclick=\"addText()\">\n"
				"\t\t\t\t\t\t\t\t  <span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span>\n"
				"\t\t\t\t\t\t\t\t</button>\n"
				"\t\t\t\t\t\t\t</div>\t\n"
				"\t\t\t\t\t\t\t<div class=\"col-lg-1\">\n"
				"\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-xs btn-default\" aria-label=\"Left Align\" onclick=\"removeText()\">\n"
				"\t\t\t\t\t\t\t\t  <span class=\"glyphicon glyphicon-minus\" aria-hidden=\"true\"></span>\n"
				"\t\t\t\t\t\t\t\t</button>\n"
				"\t\t\t\t\t\t\t</div>\t\t\t\n"
				"\t\t\t\t\t\t</div>\t\n"
				"\t\t\t\t\t</div>\n"
				"\t\t\t\t\t\n"
				"\t\t\t\t</div>\t\t\t\n"
				"\t\t\t</div>\n"
				"            <br>\n"
				"            \n"
				"            \t<div class=\"row cmvq\" id=\"precompute\" style=\"display: block; text-align:center;\">\n"
				"\n"
				"            \t\t<div class=\"col-lg-offset-3 col-lg-4\" >\n"
				"            \t\t\t<button type=\"submit\" onclick=\"precompute()\" class=\"btn btn-lg btn-primary\">Process</button>\n"
				"            \t\t</div>\n"
				"            \t</div>\n"
				"            \t<br>\n"
				"            \t<div class=\"row\">\n"
				"\n"
				"            \t\t<div class=\"col-lg-offset-3 col-lg-4\" style=\"text-align: center;\" >\n"
				"            \t\t\t<button type=\"submit\" onclick=\"run()\" class=\"btn btn-lg btn-primary\">Run</button>\n"
				"            \t\t</div>\n"
				"            \t</div>\n"
				"\t\t\t\t<br>\n"
				"\t\t\t\t            \n"
				"            \n"
				"\t            <div class=\"row\">\n"
				"\t        \t\t<div class=\"col-lg-7\" >\n"
				"\t        \t\t\tConsole\n"
				"\t        \t\t</div>\n"
				"\t        \t\t<div class=\"col-lg-4\" id=\"mvqViewResults\" onclick=\"mvqViewResults()\">\n"
				"\t        \t\t\t<button class=\"btn btn-sm btn-primary\">< View Results</button>\n"
				"\t        \t\t</div>\n"
				"\t        \t</div>\n"
				"\t        \t<div class=\"row boxcorner\">\n"
				"\t        \t\t<div class=\"col-lg-12\" id=\"logger\">\n"
				"\t        \t\t\t";
			#line 392 "./templates/my_index.tmpl"
			if(!(content.messages.empty())) {
				#line 393 "./templates/my_index.tmpl"
				out()<<"\n"
					"\t        \t\t\t\t";
				#line 393 "./templates/my_index.tmpl"
				if((content.messages).begin()!=(content.messages).end()) {
					#line 394 "./templates/my_index.tmpl"
					out()<<"\n"
						"\t\t\t\t\t\t\t";
					#line 394 "./templates/my_index.tmpl"
					for(CPPCMS_TYPEOF((content.messages).begin()) m_ptr=(content.messages).begin(),m_ptr_end=(content.messages).end();m_ptr!=m_ptr_end;++m_ptr) {
					#line 394 "./templates/my_index.tmpl"
					CPPCMS_TYPEOF(*m_ptr) &m=*m_ptr;
						#line 395 "./templates/my_index.tmpl"
						out()<<"\n"
							"\t\t\t\t\t\t    \t";
						#line 395 "./templates/my_index.tmpl"
						out()<<cppcms::filters::escape(m);
						#line 396 "./templates/my_index.tmpl"
						out()<<"\n"
							"\t\t\t\t\t\t\t";
					#line 396 "./templates/my_index.tmpl"
					} // end of item
					#line 397 "./templates/my_index.tmpl"
					out()<<"\n"
						"\t\t\t\t\t\t    ";
				#line 397 "./templates/my_index.tmpl"
				}
				#line 398 "./templates/my_index.tmpl"
				out()<<"\n"
					"\t        \t\t\t";
			#line 398 "./templates/my_index.tmpl"
			} // endif
			#line 536 "./templates/my_index.tmpl"
			out()<<"\n"
				"\t        \t\t</div>\n"
				"\t        \t</div>\n"
				"\t        \t<div class=\"row\" style=\"float:right; margin-right:10px; margin-top:10px;\">\n"
				"\t        \t\t<button type=\"button\" class=\"btn btn-xs btn-default\" aria-label=\"Left Align\" data-toggle=\"modal\" data-target=\".bs-example-modal-sm\">\n"
				"\t\t\t\t\t  <span class=\"glyphicon glyphicon-question-sign\" aria-hidden=\"true\"></span>\n"
				"\t\t\t\t\t</button>\n"
				"\t        \t</div>\n"
				"        </div>\n"
				"            \n"
				"                \n"
				"            \n"
				"            \n"
				"            \t\n"
				"                \n"
				"            \n"
				"    </div>\n"
				"</div>\n"
				"\n"
				"<div class=\"modal fade bs-example-modal-sm\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\">\n"
				"  <div class=\"modal-dialog modal-sm\" role=\"document\">\n"
				"    <div class=\"modal-content\">\n"
				"      \t<h3>Key Controls</h3>\n"
				"      \t<div class=\"row\">\n"
				"      \t\t<div class=\"col-lg-6\"></div>\n"
				"      \t</div>\n"
				"    </div>\n"
				"  </div>\n"
				"</div>\n"
				"\n"
				"\n"
				"\n"
				"\n"
				"\n"
				"<script src=\"/js/myjs.js\"></script>\n"
				"<script>\n"
				"\tif (!Detector.webgl) Detector.addGetWebGLMessage();\n"
				"\n"
				"\tvar mode;\n"
				"\n"
				"\tvar container, stats;\n"
				"\tvar camera, scene, renderer;\n"
				"\tvar controls;\n"
				"\tvar delta = 0.1;\n"
				"\tvar objects = [];\n"
				"\tvar objectsHidden = false;\n"
				"\tvar tempqp = [];\n"
				"\tvar querypoints = [];\n"
				"\tvar qpLoaded = false;\n"
				"\tvar targetpathSelected = false;\n"
				"\tvar cmvqTargetPath = [];\n"
				"\tvar cmvqCurrentTargetPos;\n"
				"\tvar cmvqTarget = null;\n"
				"\tvar cmvqTargetMark = null;\n"
				"\tvar targetSize = 2;\n"
				"\t//var obstaclePath = \"obstacles2.txt\";\n"
				"\tvar queryPath = \"querypoints.txt\";\n"
				"\tvar qp = -1;\t// which query point drawing now\n"
				"\tvar prevqp = null;\n"
				"\tvar tempqpRendered = [];\n"
				"\tvar qpRendered = [];\n"
				"\tvar rankMarkRendered = [];\n"
				"\tvar qpGroupRendered = [];\n"
				"\n"
				"\tvar vcmArray = [];\n"
				"\tvar maxseg;\n"
				"\tvar nseg;\n"
				"\tvar curseg = 0;\n"
				"\tvar totp;\n"
				"\tvar dir = 1;\n"
				"\tvar vcmGroup = null;\n"
				"\n"
				"\tvar raycaster, mouse, particleMaterial;\n"
				"\n"
				"\tvar target = [];\n"
				"\tvar targetSet = false;\n"
				"\tvar dbLoaded = false;\n"
				"\n"
				"\tvar prevPick = null;\n"
				"\tvar prevQPPick = null;\n"
				"\n"
				"\tvar k_ans;\n"
				"\n"
				"\tvar qpointdb = []\n"
				"\tvar cmvqobjects = []\n"
				"\tvar qpRenderedCMVQ = []\n"
				"\n"
				"\t// text stuff\n"
				"\tvar textGroup, textMesh1, textMesh2, textGeo, textMaterial;\n"
				"\tvar firstLetter = true;\n"
				"\tvar text = \"three.js\",\n"
				"\t\t\t\theight = 0.01,\n"
				"\t\t\t\tsize = 2.5,\n"
				"\t\t\t\thover = 0,\n"
				"\t\t\t\tcurveSegments = 12,\n"
				"\t\t\t\tbevelThickness = 0,\n"
				"\t\t\t\tbevelSize = 0,\n"
				"\t\t\t\tbevelSegments = 0,\n"
				"\t\t\t\tbevelEnabled = false,\n"
				"\t\t\t\tfont = undefined,\n"
				"\t\t\t\tfontName = \"optimer\", // helvetiker, optimer, gentilis, droid sans, droid serif\n"
				"\t\t\t\tfontWeight = \"bold\";\n"
				"\n"
				"\t// mvq sprites\n"
				"\tvar sprite1, mapA, mapB, materialA, materialB;\n"
				"\n"
				"\tvar mvqHTML;\n"
				"\t\n"
				"\tvar camera2;\n"
				"\n"
				"\tvar $textID = 1;\n"
				"\tvar vcmMesh = null;\n"
				"\n"
				"\t// for drawing MVQ visibility planes\n"
				"\tvar boxPlanes = [];\n"
				"\tvar plane0 = [0, 1, 2, 3];\n"
				"\tvar plane1 = [4, 5, 6, 7];\n"
				"\tvar plane2 = [1, 5, 6, 2];\n"
				"\tvar plane3 = [0, 4, 7, 3];\n"
				"\tvar plane4 = [0, 4, 5, 1];\n"
				"\tvar plane5 = [3, 7, 6, 2];\n"
				"\n"
				"\tboxPlanes.push(plane0); boxPlanes.push(plane1); boxPlanes.push(plane2); \n"
				"\tboxPlanes.push(plane3); boxPlanes.push(plane4); boxPlanes.push(plane5);\n"
				"\n"
				"\tvar cornerPoints = [];\n"
				"\n"
				"\tinit();\n"
				"\tanimate();\n"
				"\n"
				"\t\n"
				"\n"
				"</script>\n"
				"\n"
				"\n"
				"</body>\n"
				"</html>\n"
				"\n"
				"";
		#line 536 "./templates/my_index.tmpl"
		} // end of template render
	#line 537 "./templates/my_index.tmpl"
	}; // end of class index
#line 538 "./templates/my_index.tmpl"
} // end of namespace my_index
#line 538 "./templates/my_index.tmpl"
namespace {
#line 538 "./templates/my_index.tmpl"
 cppcms::views::generator my_generator; 
#line 538 "./templates/my_index.tmpl"
 struct loader { 
#line 538 "./templates/my_index.tmpl"
  loader() { 
#line 538 "./templates/my_index.tmpl"
   my_generator.name("my_index");
#line 538 "./templates/my_index.tmpl"
   my_generator.add_view<my_index::index,content::index_content>("index",true);
#line 538 "./templates/my_index.tmpl"
    cppcms::views::pool::instance().add(my_generator);
#line 538 "./templates/my_index.tmpl"
 }
#line 538 "./templates/my_index.tmpl"
 ~loader() {  cppcms::views::pool::instance().remove(my_generator); }
#line 538 "./templates/my_index.tmpl"
} a_loader;
#line 538 "./templates/my_index.tmpl"
} // anon 
